/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import static shootingspaceship.BackgroundMove.bg;
import shootingspaceship.Sound;
import shootingspaceship.Shootingspaceship;
import static shootingspaceship.Shootingspaceship.weapon;
import static shootingspaceship.Shootingspaceship.width;
import static ui.WeaponChoice.weaponNum;

/**
 *
 * @author Seo
 */
public class Intro extends javax.swing.JFrame {
    public static Shootingspaceship ship;
    public static Thread th;
    public static JFrame frame;
    public static Intro intro;
    //public static Image bg;
    
    //private Image screenImage;
    //private Graphics screenGraphic;
    
    //private Image introBG;
    
    public static int selectCharacter = 0;
    private Sound introBGM;
    private boolean isManCharacterSelected = false;
    private boolean isGirlCharacterSelected = false;
    
    public Intro() {
        initComponents();
        introBGM = new Sound("IntroMusic.mp3",true);
        setPreferredSize(new Dimension(1200, 900));
        setTitle("학교생활 살아남기");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectGirl = new javax.swing.JLabel();
        SelectMan = new javax.swing.JLabel();
        StartBt = new javax.swing.JLabel();
        ChooseWeapon = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        ExitBt = new javax.swing.JLabel();
        GameName = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setName("intro"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setResizable(false);

        SelectGirl.setBackground(new java.awt.Color(255, 255, 255));
        SelectGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerGirlWait.png"))); // NOI18N
        SelectGirl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SelectGirl.setFocusable(false);
        SelectGirl.setMaximumSize(new java.awt.Dimension(300, 285));
        SelectGirl.setMinimumSize(new java.awt.Dimension(300, 285));
        SelectGirl.setName("playerGirl"); // NOI18N
        SelectGirl.setPreferredSize(new java.awt.Dimension(300, 285));
        SelectGirl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SelectGirlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SelectGirlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SelectGirlMousePressed(evt);
            }
        });

        SelectMan.setBackground(new java.awt.Color(255, 255, 255));
        SelectMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerManWait.png"))); // NOI18N
        SelectMan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SelectMan.setFocusable(false);
        SelectMan.setMaximumSize(new java.awt.Dimension(300, 285));
        SelectMan.setMinimumSize(new java.awt.Dimension(300, 285));
        SelectMan.setName("playerGirl"); // NOI18N
        SelectMan.setPreferredSize(new java.awt.Dimension(300, 285));
        SelectMan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SelectManMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SelectManMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SelectManMousePressed(evt);
            }
        });

        StartBt.setBackground(new java.awt.Color(255, 255, 255));
        StartBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/StartBt.png"))); // NOI18N
        StartBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StartBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StartBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StartBtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StartBtMousePressed(evt);
            }
        });

        ChooseWeapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/ChooseWeapon.png"))); // NOI18N
        ChooseWeapon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChooseWeapon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChooseWeaponMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChooseWeaponMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ChooseWeaponMousePressed(evt);
            }
        });

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/HelpBt.png"))); // NOI18N
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpMousePressed(evt);
            }
        });

        ExitBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/ExitBt.png"))); // NOI18N
        ExitBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitBtMousePressed(evt);
            }
        });

        GameName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/GameName.png"))); // NOI18N

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/IntroBG.png"))); // NOI18N
        backGround.setAlignmentY(0.0F);
        backGround.setIconTextGap(0);
        backGround.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SelectMan, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SelectGirl, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(help)
                                            .addComponent(StartBt)
                                            .addComponent(ExitBt, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(371, 371, 371))))
                            .addComponent(GameName, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(ChooseWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backGround)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GameName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SelectGirl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(StartBt)
                .addGap(18, 18, 18)
                .addComponent(help)
                .addGap(18, 18, 18)
                .addComponent(ChooseWeapon)
                .addGap(18, 18, 18)
                .addComponent(ExitBt)
                .addGap(45, 45, 45))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backGround)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        SelectGirl.getAccessibleContext().setAccessibleDescription("");

        setBounds(0, 0, 1218, 947);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtMousePressed
        // TODO add your handling code here:
        Sound pressedSound = new Sound("buttonPressed.mp3", false);
        pressedSound.start();
        System.exit(0);
    }//GEN-LAST:event_ExitBtMousePressed

    private void ExitBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtMouseExited
        // TODO add your handling code here:
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        enteredSound.start();

        ExitBt.setLocation(ExitBt.getX() - 2 , ExitBt.getY() - 2 );
    }//GEN-LAST:event_ExitBtMouseExited

    private void ExitBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtMouseEntered
        // TODO add your handling code here:
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        enteredSound.start();

        ExitBt.setLocation(ExitBt.getX() + 2 , ExitBt.getY() + 2 );
    }//GEN-LAST:event_ExitBtMouseEntered

    private void ChooseWeaponMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseWeaponMousePressed
        // TODO add your handling code here:
        Sound pressedSound = new Sound("buttonPressed.mp3", false);
        pressedSound.start();

        new WeaponChoice().setVisible(true);
    }//GEN-LAST:event_ChooseWeaponMousePressed

    private void ChooseWeaponMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseWeaponMouseExited
        // TODO add your handling code here:
        ChooseWeapon.setLocation(ChooseWeapon.getX() - 2, ChooseWeapon.getY() - 2);
    }//GEN-LAST:event_ChooseWeaponMouseExited

    private void ChooseWeaponMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseWeaponMouseEntered
        // TODO add your handling code here:
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        ChooseWeapon.setLocation(ChooseWeapon.getX() + 2,ChooseWeapon.getY() + 2);
        enteredSound.start();
    }//GEN-LAST:event_ChooseWeaponMouseEntered

    private void helpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMousePressed
        // TODO add your handling code here:
        Sound pressedSound = new Sound("buttonPressed.mp3", false);
        pressedSound.start();
        new Help().setVisible(true);
    }//GEN-LAST:event_helpMousePressed

    private void helpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseExited
        // TODO add your handling code here:
        help.setLocation(help.getX() - 2, help.getY() - 2);
    }//GEN-LAST:event_helpMouseExited

    private void helpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseEntered
        // TODO add your handling code here:
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        enteredSound.start();
        help.setLocation(help.getX() + 2, help.getY() + 2);
    }//GEN-LAST:event_helpMouseEntered

    private void StartBtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtMousePressed
        introBGM.close();
        InGameUI inGameUI = new InGameUI();
        ship = new Shootingspaceship(inGameUI);
        ship.setStartStage();
        ship.setSelectWeapon(WeaponChoice.weaponNum);
        ship.setSelectCharater(selectCharacter);
        
        
        th = new Thread(ship);
        frame = new JFrame("Shooting");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(ship);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.add(inGameUI, BorderLayout.SOUTH);
        
        Sound pressedSound = new Sound("buttonPressed.mp3", false);
        pressedSound.start();
        introBGM.close();
        try{
            Thread.sleep(1000);
        }catch(InterruptedException e){
            e.printStackTrace();
        }
        System.out.println("th.start");
        th.start();
        
        System.out.println("intro setVisivble : true");
        frame.setVisible(true);
        this.setVisible(false);
        //frame.dispose();
//
        
        
        
        //dispose();
    }//GEN-LAST:event_StartBtMousePressed

    private void StartBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtMouseExited
        StartBt.setLocation(StartBt.getX() - 2,StartBt.getY() - 2);
    }//GEN-LAST:event_StartBtMouseExited

    private void StartBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtMouseEntered
        // TODO add your handling code here:
        StartBt.setLocation(StartBt.getX() + 2,StartBt.getY() + 2);
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        enteredSound.start();

    }//GEN-LAST:event_StartBtMouseEntered

    private void SelectGirlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectGirlMousePressed
        SelectMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon" + weaponNum + ".png")));
        SelectGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerGirl.png")));
        selectCharacter = 1;
        
        isGirlCharacterSelected = true;
        isManCharacterSelected = false;
        
        Sound pressedSound = new Sound("buttonPressed.mp3", false);
        pressedSound.start();
        System.out.println("여캐 클릭 : 캐릭터 여캐");

    }//GEN-LAST:event_SelectGirlMousePressed

    private void SelectGirlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectGirlMouseExited
        if(!isManCharacterSelected)
            SelectGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerGirlWait.png")));
        else if(isManCharacterSelected)
            SelectGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon" + weaponNum + ".png")));
    }//GEN-LAST:event_SelectGirlMouseExited

    private void SelectGirlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectGirlMouseEntered
        if(!isManCharacterSelected)
            SelectGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerGirl.png")));
        else if(isManCharacterSelected)
            SelectGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerGirlWait.png")));
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        enteredSound.start();
    }//GEN-LAST:event_SelectGirlMouseEntered

    private void SelectManMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectManMousePressed
        SelectGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon" + weaponNum + ".png")));
        SelectMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerMan.png")));
        
        isManCharacterSelected = true;
        isGirlCharacterSelected = false;
        
        selectCharacter = 0;
        Sound pressedSound = new Sound("buttonPressed.mp3", false);
        pressedSound.start();
        System.out.println("남캐 클릭 : 캐릭터 남캐");

    }//GEN-LAST:event_SelectManMousePressed

    private void SelectManMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectManMouseExited
        if(!isGirlCharacterSelected)
            SelectMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerManWait.png")));
        else if(isGirlCharacterSelected)
            SelectMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon" + weaponNum + ".png")));
    }//GEN-LAST:event_SelectManMouseExited

    private void SelectManMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectManMouseEntered
        if(!isGirlCharacterSelected)
            SelectMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerMan.png")));
        else if(isGirlCharacterSelected)
            SelectMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/PlayerManWait.png")));
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        enteredSound.start();
    }//GEN-LAST:event_SelectManMouseEntered
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                intro = new Intro();
                intro.setVisible(true);
                intro.introBGM.start();
                intro.backGround.setLocation(0,0);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChooseWeapon;
    private javax.swing.JLabel ExitBt;
    private javax.swing.JLabel GameName;
    static javax.swing.JLabel SelectGirl;
    static javax.swing.JLabel SelectMan;
    private javax.swing.JLabel StartBt;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel help;
    // End of variables declaration//GEN-END:variables
}
