/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Seo
 */
public class ScoreBoard extends javax.swing.JFrame {

    /**
     * Creates new form ScoreBord
     */
    public ScoreBoard() {
        
        initComponents();
        getContentPane().setBackground(new Color(208,231,239));
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name5 = new javax.swing.JLabel();
        Name6 = new javax.swing.JLabel();
        Name8 = new javax.swing.JLabel();
        Name7 = new javax.swing.JLabel();
        Name9 = new javax.swing.JLabel();
        Name10 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        Name4 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Score5 = new javax.swing.JLabel();
        Score6 = new javax.swing.JLabel();
        Score8 = new javax.swing.JLabel();
        Score7 = new javax.swing.JLabel();
        Score9 = new javax.swing.JLabel();
        Score10 = new javax.swing.JLabel();
        Score3 = new javax.swing.JLabel();
        Score4 = new javax.swing.JLabel();
        Score2 = new javax.swing.JLabel();
        Score1 = new javax.swing.JLabel();
        Rank21 = new javax.swing.JLabel();
        Rank22 = new javax.swing.JLabel();
        Rank23 = new javax.swing.JLabel();
        Rank24 = new javax.swing.JLabel();
        Rank25 = new javax.swing.JLabel();
        Rank26 = new javax.swing.JLabel();
        Rank27 = new javax.swing.JLabel();
        Rank28 = new javax.swing.JLabel();
        Rank29 = new javax.swing.JLabel();
        Rank30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        playerName = new javax.swing.JLabel();
        playerScore = new javax.swing.JLabel();
        playerGrade = new javax.swing.JLabel();
        playerRank = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 102));
        setMinimumSize(new java.awt.Dimension(700, 600));

        Name5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name5.setText("jLabel1");

        Name6.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name6.setText("jLabel1");

        Name8.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name8.setText("jLabel1");

        Name7.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name7.setText("jLabel1");

        Name9.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name9.setText("jLabel1");

        Name10.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name10.setText("jLabel1");

        Name3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name3.setText("jLabel1");

        Name4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name4.setText("jLabel1");

        Name2.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name2.setText("jLabel1");

        Name1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Name1.setText("jLabel1");

        Score5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score5.setText("jLabel1");

        Score6.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score6.setText("jLabel1");

        Score8.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score8.setText("jLabel1");

        Score7.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score7.setText("jLabel1");

        Score9.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score9.setText("jLabel1");

        Score10.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score10.setText("jLabel1");

        Score3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score3.setText("jLabel1");

        Score4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score4.setText("jLabel1");

        Score2.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score2.setText("jLabel1");

        Score1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Score1.setText("jLabel1");

        Rank21.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank21.setText("5");

        Rank22.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank22.setText("6");

        Rank23.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank23.setText("8");

        Rank24.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank24.setText("7");

        Rank25.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank25.setText("9");

        Rank26.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank26.setText("10");

        Rank27.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank27.setText("3");

        Rank28.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank28.setText("4");

        Rank29.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank29.setText("2");

        Rank30.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        Rank30.setText("1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/title.png"))); // NOI18N

        playerName.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        playerName.setText("jLabel1");

        playerScore.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        playerScore.setText("jLabel1");

        playerGrade.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        playerGrade.setText("jLabel1");

        playerRank.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        playerRank.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playerName, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(playerScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerRank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Rank22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rank21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rank24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rank23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rank25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Rank29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rank30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rank27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rank28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rank26, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Name6)
                    .addComponent(Name7)
                    .addComponent(Name8)
                    .addComponent(Name9)
                    .addComponent(Name10)
                    .addComponent(Name1)
                    .addComponent(Name2)
                    .addComponent(Name3)
                    .addComponent(Name4)
                    .addComponent(Name5))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Score6)
                    .addComponent(Score7)
                    .addComponent(Score8)
                    .addComponent(Score9)
                    .addComponent(Score10)
                    .addComponent(Score5)
                    .addComponent(Score4)
                    .addComponent(Score3)
                    .addComponent(Score2)
                    .addComponent(Score1))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerName)
                        .addGap(18, 18, 18)
                        .addComponent(playerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(playerGrade)
                        .addGap(20, 20, 20)
                        .addComponent(playerRank))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Rank30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rank29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rank27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rank28)
                        .addGap(12, 12, 12)
                        .addComponent(Rank21)
                        .addGap(13, 13, 13)
                        .addComponent(Rank22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rank24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rank23)
                        .addGap(18, 18, 18)
                        .addComponent(Rank25)
                        .addGap(18, 18, 18)
                        .addComponent(Rank26))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Score1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Score2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Score3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Score4)
                            .addGap(12, 12, 12)
                            .addComponent(Score5)
                            .addGap(13, 13, 13)
                            .addComponent(Score6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Score7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Score8)
                            .addGap(18, 18, 18)
                            .addComponent(Score9)
                            .addGap(18, 18, 18)
                            .addComponent(Score10))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Name1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Name2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Name3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Name4)
                            .addGap(12, 12, 12)
                            .addComponent(Name5)
                            .addGap(13, 13, 13)
                            .addComponent(Name6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Name7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Name8)
                            .addGap(18, 18, 18)
                            .addComponent(Name9)
                            .addGap(18, 18, 18)
                            .addComponent(Name10))))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Name1;
    public javax.swing.JLabel Name10;
    public javax.swing.JLabel Name2;
    public javax.swing.JLabel Name3;
    public javax.swing.JLabel Name4;
    public javax.swing.JLabel Name5;
    public javax.swing.JLabel Name6;
    public javax.swing.JLabel Name7;
    public javax.swing.JLabel Name8;
    public javax.swing.JLabel Name9;
    private javax.swing.JLabel Rank21;
    private javax.swing.JLabel Rank22;
    private javax.swing.JLabel Rank23;
    private javax.swing.JLabel Rank24;
    private javax.swing.JLabel Rank25;
    private javax.swing.JLabel Rank26;
    private javax.swing.JLabel Rank27;
    private javax.swing.JLabel Rank28;
    private javax.swing.JLabel Rank29;
    private javax.swing.JLabel Rank30;
    public javax.swing.JLabel Score1;
    public javax.swing.JLabel Score10;
    public javax.swing.JLabel Score2;
    public javax.swing.JLabel Score3;
    public javax.swing.JLabel Score4;
    public javax.swing.JLabel Score5;
    public javax.swing.JLabel Score6;
    public javax.swing.JLabel Score7;
    public javax.swing.JLabel Score8;
    public javax.swing.JLabel Score9;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel playerGrade;
    public javax.swing.JLabel playerName;
    public javax.swing.JLabel playerRank;
    public javax.swing.JLabel playerScore;
    // End of variables declaration//GEN-END:variables
}
