/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ImageIcon;
import shootingspaceship.Sound;
import static ui.Intro.*;

/**
 *
 * @author Seo
 */

public class WeaponChoice extends javax.swing.JFrame {
    public static int weaponNum = 0;
    private static void setIcon(ImageIcon imageIcon) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form ChoseWeapon
     */
    public WeaponChoice() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(600, 799));
       
    }
    private void choseWeapon() {
        switch(weaponNum) {
            case 0:
                Weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon0.png")));
                Department.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weaponName0.png")));
                backGround.setIcon(new ImageIcon(getClass().getResource("/image/UIImage/weapon0BG.jpg")));
                explain_.setIcon(new ImageIcon(getClass().getResource("/image/UIImage/weapon0ex.png")));
                break;
            case 1:
                Weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon1.png")));
                Department.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weaponName1.png")));
                backGround.setIcon(new ImageIcon(getClass().getResource("/image/UIImage/weapon1BG.jpg")));
                explain_.setIcon(new ImageIcon(getClass().getResource("/image/UIImage/weapon1ex.png")));
                break;
            case 2:
                Weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon2.png")));
                Department.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weaponName2.png")));
                backGround.setIcon(new ImageIcon(getClass().getResource("/image/UIImage/weapon2BG.jpg")));
                explain_.setIcon(new ImageIcon(getClass().getResource("/image/UIImage/weapon2ex.png")));
                break;
            case 3:
                Weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon3.png")));
                Department.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weaponName3.png")));
                backGround.setIcon(new ImageIcon(getClass().getResource("/image/UIImage/weapon3BG.jpg")));
                explain_.setIcon(new ImageIcon(getClass().getResource("/image/UIImage/weapon3ex.png")));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Weapon = new javax.swing.JLabel();
        Next = new javax.swing.JLabel();
        Prev = new javax.swing.JLabel();
        Select = new javax.swing.JLabel();
        Department = new javax.swing.JLabel();
        explain = new javax.swing.JLabel();
        explain_ = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("무기 선택");
        setMaximumSize(new java.awt.Dimension(600, 799));
        setMinimumSize(new java.awt.Dimension(600, 799));

        Weapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon0.png"))); // NOI18N

        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/next.png"))); // NOI18N
        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NextMousePressed(evt);
            }
        });

        Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/prev.png"))); // NOI18N
        Prev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PrevMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrevMousePressed(evt);
            }
        });

        Select.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/select.png"))); // NOI18N
        Select.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SelectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SelectMousePressed(evt);
            }
        });

        Department.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weaponName0.png"))); // NOI18N

        explain_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon0ex.png"))); // NOI18N

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon0BG.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Weapon)
                        .addGap(18, 18, 18)
                        .addComponent(Next))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(Department))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(explain))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(explain_))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(Select)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backGround)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(Department)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Weapon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(Next))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(Prev)))
                .addGap(56, 56, 56)
                .addComponent(explain_)
                .addGap(84, 84, 84)
                .addComponent(Select)
                .addGap(80, 80, 80)
                .addComponent(explain))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backGround)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectMousePressed
        // TODO add your handling code here:
        Sound pressedSound = new Sound("buttonPressed.mp3", false);
        pressedSound.start();
        if(selectCharacter == 0){
            SelectGirl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon" + weaponNum+ ".png")));
            SelectGirl.setVisible(true);
        }
        else{
            SelectMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UIImage/weapon" + weaponNum+ ".png")));
            SelectMan.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_SelectMousePressed

    private void SelectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectMouseExited
        // TODO add your handling code here:
        Select.setLocation(Select.getX() - 2, Select.getY() - 2);
    }//GEN-LAST:event_SelectMouseExited

    private void SelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectMouseEntered
        // TODO add your handling code here:
        Select.setLocation(Select.getX() + 2, Select.getY() + 2);
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        enteredSound.start();
    }//GEN-LAST:event_SelectMouseEntered

    private void PrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevMousePressed
        // TODO add your handling code here:
        if(weaponNum > 0){
            --weaponNum;
        }
        else weaponNum = 3;
        //System.out.println(weaponNum);
        choseWeapon();
        Sound pressedSound = new Sound("buttonPressed.mp3", false);
        pressedSound.start();
    }//GEN-LAST:event_PrevMousePressed

    private void PrevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevMouseExited
        // TODO add your handling code here:
        Prev.setLocation(Prev.getX() - 2, Prev.getY() - 2);
    }//GEN-LAST:event_PrevMouseExited

    private void PrevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevMouseEntered
        // TODO add your handling code here:
        Prev.setLocation(Prev.getX() + 2, Prev.getY() + 2);
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        enteredSound.start();
    }//GEN-LAST:event_PrevMouseEntered

    private void NextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMousePressed
        // TODO add your handling code here:
        //이미지 바꾸고,
        if(weaponNum < 3){
            ++weaponNum;
        }
        else weaponNum = 0;
        //System.out.println(weaponNum);
        choseWeapon();
        Sound pressedSound = new Sound("buttonPressed.mp3", false);
        pressedSound.start();
    }//GEN-LAST:event_NextMousePressed

    private void NextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseExited
        // TODO add your handling code here:
        Next.setLocation(Next.getX() - 2, Next.getY() - 2);
    }//GEN-LAST:event_NextMouseExited

    private void NextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseEntered
        // TODO add your handling code here:
        Next.setLocation(Next.getX() + 2, Next.getY() + 2);
        Sound enteredSound = new Sound("buttonEntered.mp3", false);
        enteredSound.start();
    }//GEN-LAST:event_NextMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeaponChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeaponChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeaponChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeaponChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WeaponChoice wc;
                wc = new WeaponChoice();
                wc.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Department;
    private javax.swing.JLabel Next;
    private javax.swing.JLabel Prev;
    private javax.swing.JLabel Select;
    private javax.swing.JLabel Weapon;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel explain;
    private javax.swing.JLabel explain_;
    // End of variables declaration//GEN-END:variables
}
